// ZCam Camera HTTP Commands
// 基于 zcam http commands breif.md 文档生成

// 多语言描述映射表
const commandDescriptions = {
  zh: {
    "camera info": "得到相机信息",
    "camera sn": "获取相机序列号",
    "commit info": "获取提交信息",
    "nick name": "获取昵称",
    "camera status": "获取相机状态",
    "check session status": "检查会话状态",
    "occupy the session": "占用会话",
    "quit the session": "退出会话",
    "clear setting": "清除相机所有设置",
    "temperature": "相机温度",
    "battery_voltage": "获取电池电压",
    "battery": "获取电池状态",
    "raw over hdmi": "HDMI原始输出",
    "led on/off": "LED开关状态",
    "desqueeze": "去挤压设置",
    "export profile": "导出配置文件",
    "working mode": "查询工作模式",
    "to record mode": "切换到视频录制模式",
    "to playback mode": "切换到视频播放模式",
    "to standby": "切换到待机模式",
    "exit standby": "退出待机模式",
    "record mode": "获取录制模式",
    "start record": "开始录制",
    "stop record": "停止录制",
    "get record status": "获取录制状态",
    "get recording duration": "获取录制时长",
    "remain recording time": "查询剩余录制时间",
    "repair status": "获取修复状态",
    "set record meta": "设置录制元数据",
    "get record meta option": "获取录制元数据选项",
    "get camera id": "获取相机ID",
    "set camera id": "设置相机ID",
    "get reel name": "获取卷名",
    "set reel name": "设置卷名",
    "record format": "获取录制格式",
    "record file rotation": "获取录制文件旋转",
    "record split duration": "获取录制分割时长",
    "record frame indicator": "获取录制帧指示器",
    "preroll enable": "获取预卷启用状态",
    "preroll duration": "获取预卷时长",
    "mov format": "获取MOV格式",
    "resolution": "获取分辨率",
    "project fps": "获取项目帧率",
    "vfr control": "获取可变帧率控制",
    "mov vfr": "获取MOV可变帧率",
    "record fps": "获取录制帧率",
    "photo quality": "获取照片质量",
    "photo capture": "拍摄照片",
    "multiple cam mode": "获取多相机模式",
    "union auto exposure": "获取联合自动曝光",
    "union auto white balance": "获取联合自动白平衡",
    "ezlink mode": "获取EZLink模式",
    "ezlink trigger": "获取EZLink触发模式",
    "pixel link role": "查询硬件同步角色",
    "shutdown": "关机",
    "reboot": "重启",
    "auto off": "获取自动关机设置",
    "set auto off": "设置自动关机",
    "auto standby": "获取自动待机设置",
    "set auto standby": "设置自动待机",
    "query timecode": "查询时间码",
    "reset timecode": "重置时间码",
    "set current timecode": "设置当前时间码",
    "set manual timecode": "设置手动时间码",
    "tc source": "获取时间码源",
    "tc count up": "获取时间码计数模式",
    "tc hdmi display": "获取HDMI时间码显示",
    "tc drop frame option": "获取时间码丢帧选项",
    "genlock status": "获取同步锁状态",
    "genlock coarse": "获取同步锁粗调",
    "genlock fine": "获取同步锁微调",
    "sync camera time": "同步相机时间",
    "set timezone": "设置时区",
    "get date time": "获取日期时间",
    "ntp time start": "启动NTP时间同步",
    "ntp time stop": "停止NTP时间同步",
    "get ntp status": "获取NTP状态",
    "set ntp interval": "设置NTP间隔",
    "upload new firmware": "上传新固件",
    "refresh firmware": "刷新固件",
    "check firmware": "检查固件",
    "ui check firmware": "UI检查固件",
    "batch get record settings": "批量获取录制设置",
    "batch get video settings": "批量获取视频设置",
    "batch get audio settings": "批量获取音频设置",
    "batch get image settings": "批量获取图像设置",
    "batch get exposure settings": "批量获取曝光设置",
    "batch get white balance settings": "批量获取白平衡设置",
    "batch get lens settings": "批量获取镜头设置",
    "batch get assist tools settings": "批量获取辅助工具设置",
    "batch get timecode settings": "批量获取时间码设置",
    "batch get multi camera settings": "批量获取多相机设置",
    "batch get network settings": "批量获取网络设置",
    "batch get security settings": "批量获取安全设置",
    "batch get system settings": "批量获取系统设置",
    "batch get maintenance settings": "批量获取维护设置",
    "video encoder": "获取视频编码器",
    "bitrate level": "获取比特率级别",
    "compose mode WDR": "获取合成模式(WDR)",
    "eis on off": "获取电子防抖开关",
    "video rotation": "获取视频旋转",
    "video timelapse interval": "获取视频延时摄影间隔",
    "low jello": "获取低果冻效果",
    "crop sensor": "裁剪传感器",
    "audio encoder": "获取音频编码器",
    "audio source": "获取音频源",
    "audio phantom power": "获取音频幻象电源",
    "audio level display": "获取音频电平显示",
    "audio gain type": "获取音频增益类型",
    "audio input level": "获取音频输入电平",
    "audio input gain": "获取音频输入增益",
    "audio input left gain": "获取左声道输入增益",
    "audio input right gain": "获取右声道输入增益",
    "audio output gain": "获取音频输出增益",
    "audio noise reduction": "获取音频降噪设置",
    "white balance mode": "获取白平衡模式",
    "manual kelvin": "获取手动色温",
    "manual tint": "获取手动色调",
    "manual R": "获取手动红色",
    "manual G": "获取手动绿色",
    "manual B": "获取手动蓝色",
    "auto white balance priority": "获取自动白平衡优先级",
    "lock awb in recording": "获取录制时锁定自动白平衡",
    "ev": "获取曝光值",
    "flicker": "获取闪烁设置",
    "meter mode": "获取测光模式",
    "iris aperture": "获取光圈值",
    "iso options": "获取ISO选项",
    "min iso": "获取最小ISO",
    "max iso": "获取最大ISO",
    "iso control": "获取ISO控制",
    "shutter angle control": "获取快门角度控制",
    "shutter operation": "获取快门操作",
    "max exposure shutter time": "获取最大曝光快门时间",
    "elec ND": "获取电子ND",
    "auto exposure speed": "获取自动曝光速度",
    "black light comp": "获取黑光补偿",
    "live ae shutter speed": "获取实时自动曝光快门速度",
    "live ae shutter angle": "获取实时自动曝光快门角度",
    "live ae iso": "获取实时自动曝光ISO",
    "ev choice": "获取曝光值选择",
    "shutter time": "获取快门时间",
    "shutter angle": "获取快门角度",
    "lock ae in record": "获取录制时锁定自动曝光",
    "image profile": "获取图像配置文件",
    "image noise reduction": "获取图像降噪设置",
    "image luma level": "获取图像亮度级别",
    "image sharpness": "获取图像锐度",
    "image brightness": "获取图像亮度",
    "image contrast": "获取图像对比度",
    "image saturation": "获取图像饱和度",
    "image hue": "获取图像色调",
    "image dro": "获取图像动态范围优化",
    "image vignette": "获取图像暗角效果",
    "image matrix": "查询图像矩阵",
    "enable image matrix": "启用图像矩阵",
    "set image matrix value": "设置矩阵值",
    "cc option": "查询颜色校正选项",
    "enable cc": "启用颜色校正",
    "set cc hue": "设置色调",
    "set cc saturation": "设置饱和度",
    "get gamma options": "获取伽马选项",
    "set gamma power": "设置伽马功率",
    "gamma black level": "查询黑电平",
    "config gamma black level": "配置黑电平",
    "query black gamma": "查询黑伽马",
    "config black gamma": "配置黑伽马",
    "gamma knee": "查询拐点",
    "config gamma knee": "配置拐点",
    "get ip mode": "获取IP模式",
    "ethernet mode": "获取以太网模式",
    "get ip configuration": "获取IP配置",
    "DHCP router": "设置DHCP路由器模式",
    "Direct IP": "设置直接IP模式",
    "Static IP": "设置静态IP",
    "query wifi status": "查询WiFi状态",
    "get wifi options": "获取WiFi选项",
    "set wifi options": "设置WiFi选项",
    "get usb role": "获取USB角色",
    "set usb role": "设置USB角色",
    "query usb info": "查询USB信息",
    "get sdi enable/disable": "获取SDI启用状态",
    "set sdi enable/disable": "设置SDI启用状态",
    "get sdi 3g mode": "获取SDI 3G模式",
    "set sdi 3g mode": "设置SDI 3G模式",
    "get hdmi format": "获取HDMI格式",
    "set hdmi format": "设置HDMI格式",
    "get hdmi osd option": "获取HDMI OSD选项",
    "set hdmi osd option": "设置HDMI OSD选项",
    "get hdmi osd layout": "获取HDMI OSD布局",
    "set hdmi osd layout": "设置HDMI OSD布局",
    "query free-D": "查询Free-D",
    "set free-D camera id": "设置Free-D相机ID",
    "config free-D": "配置Free-D",
    "enable free-D": "启用Free-D",
    "set visca id": "设置VISCA ID",
    "set visca baudrate": "设置VISCA波特率",
    "enable visca": "启用VISCA",
    "get send stream info": "获取拉流源信息",
    "send stream0": "切换拉流源到Stream0",
    "send stream1": "切换拉流源到Stream1",
    "stream0 settings": "查询stream0设置",
    "stream1 settings": "查询stream1设置",
    "change stream1 bitrate": "更改stream1比特率",
    "change stream1 width height": "更改stream1分辨率",
    "change stream1 encoder": "更改stream1编码器",
    "change stream1 bitwidth": "更改stream1位宽",
    "get streaming resolution": "获取推流分辨率",
    "get streaming frame rate": "获取推流帧率",
    "get streaming video encoder": "获取推流视频编码器",
    "get streaming param save": "获取推流参数保存",
    "set streaming video encoder": "设置推流视频编码器",
    "query rtmp": "查询RTMP",
    "query rtsp": "查询RTSP",
    "query ndi": "查询NDI",
    "query srt": "查询SRT",
    "disable restore lens pos": "禁用恢复镜头位置",
    "enable restore lens pos": "启用恢复镜头位置",
    "get lens information": "获取镜头信息",
    "get lens focal length": "获取镜头焦距",
    "lens focus near": "对焦近",
    "lens focus far": "对焦远",
    "lens focus stop": "停止对焦",
    "lens focus status": "对焦状态",
    "trigger auto focus": "触发自动对焦",
    "af speed": "自动对焦速度",
    "focus method": "对焦方法",
    "continuous af": "连续自动对焦",
    "af flexible size": "af灵活区域大小",
    "continuous af sensitivity": "连续自动对焦灵敏度",
    "live continuous af": "实时连续自动对焦",
    "af adjust with PTZ": "PTZ对焦调整",
    "MF assist preview": "手动对焦辅助预览",
    "MF assist recording": "手动对焦辅助录制",
    "trace with face id": "按人脸ID跟踪",
    "af ROI type": "ROI类型",
    "update the ROI of af": "更新AF的ROI",
    "update the ROI of af to center": "将AF的ROI更新到中心",
    "get the ROI of af": "获取AF的ROI",
    "control the focus far/near": "控制对焦远/近",
    "get the focus position": "获取焦点位置",
    "set the focus position": "设置焦点位置",
    "zoom mode": "变焦模式",
    "zoom position": "变焦位置",
    "zoom status": "变焦状态",
    "zoom in with speed": "变焦放大",
    "zoom out": "变焦缩小",
    "stop zoom": "停止变焦",
    "zoom to a position": "变焦到指定位置",
    "pan tilt direction": "云台方向控制",
    "query pan tilt": "查询PTZ",
    "query pan tilt details": "查询PTZ详情",
    "stop pan tilt": "停止PTZ",
    "stop all pan tilt": "停止所有PTZ",
    "pan tilt direction move": "方向移动",
    "pan tilt speed": "云台和倾斜速度",
    "pan tilt home": "PTZ回中",
    "pan tilt reset": "PTZ重置",
    "pan tilt limit update": "限制更新",
    "pan tilt limit": "PTZ限制",
    "pan tilt speed mode": "速度模式",
    "pan tilt speed with zoom position": "变焦位置速度",
    "pan tilt flip": "翻转",
    "pan tilt privacy mode": "隐私模式",
    "pan tilt power on position": "开机位置",
    "PTZ preset recall": "PTZ 预设调用",
    "PTZ preset save": "PTZ 预设保存",
    "PTZ preset delete": "PTZ 预设删除",
    "PTZ preset info": "PTZ 预设信息",
    "PTZ preset name": "PTZ 预设名称",
    "PTZ preset speed unit": "PTZ 预设速度单位",
    "PTZ preset speed by duration": "按时长设置预设速度",
    "PTZ preset speed by index": "按索引设置预设速度",
    "PTZ common speed": "PTZ 通用速度",
    "PTZ common time": "PTZ 通用时间",
    "PTZ preset recall mode": "PTZ 预设调用模式",
    "PTZ recall speed mode": "PTZ 调用速度模式",
    "PTZ freeze duration recall": "PTZ 调用时冻结时长",
    "PTZ common speed unit": "PTZ 通用速度单位",
    "delete ptz trace": "删除PTZ轨迹",
    "rename ptz trace": "重命名PTZ轨迹",
    "record ptz trace start": "开始记录PTZ轨迹",
    "record ptz trace stop": "停止记录PTZ轨迹",
    "prepare play ptz trace": "准备播放PTZ轨迹",
    "play ptz trace start": "开始播放PTZ轨迹",
    "play ptz trace stop": "停止播放PTZ轨迹",
    "query ptz trace": "查询PTZ轨迹",
    "get ptz trace info": "获取PTZ轨迹信息",
    "check card present": "检查存储卡是否存在",
    "query card format": "查询存储卡格式",
    "format storage card": "格式化存储卡",
    "format to fat32": "格式化存储卡为FAT32格式",
    "format to exfat": "格式化存储卡为exFAT格式",
    "query card free space": "查询存储卡可用空间",
    "query card total space": "查询存储卡总空间",
    "list card folders": "列出存储卡中的文件夹",
    "list files in card folders": "列出存储卡文件夹中的文件",
    "download file from card": "从存储卡下载文件",
    "delete file in card": "删除存储中的文件",
    "get file thumbnail": "获取文件缩略图",
    "get file screen nail": "获取文件屏幕截图",
    "get file create time": "获取文件创建时间",
    "get file info": "获取文件信息"
  },
  
  en: {
    "camera info": "Get camera information",
    "camera sn": "Get camera serial number",
    "commit info": "Get commit information",
    "nick name": "Get nickname",
    "camera status": "Get camera status",
    "check session status": "Check session status",
    "occupy the session": "Occupy session",
    "quit the session": "Quit session",
    "clear setting": "Clear camera all settings",
    "temperature": "Camera temperature",
    "battery_voltage": "Get battery voltage",
    "battery": "Get battery status",
    "raw over hdmi": "HDMI raw output",
    "led on/off": "LED on/off status",
    "desqueeze": "Desqueeze settings",
    "export profile": "Export profile",
    "working mode": "working mode",
    "to record mode": "to record mode",
    "to playback mode": "to playback mode",
    "to standby": "Switch to standby mode",
    "exit standby": "Exit standby mode",
    "record mode": "Get record mode",
    "start record": "Start recording",
    "stop record": "Stop recording",
    "get record status": "Get record status",
    "get recording duration": "Get recording duration",
    "remain recording time": "Query remaining recording time",
    "repair status": "repair status",
    "set record meta": "Set record metadata",
    "get record meta option": "Get record metadata options",
    "get camera id": "Get camera ID",
    "set camera id": "Set camera ID",
    "get reel name": "Get reel name",
    "set reel name": "Set reel name",
    "record format": "Get record format",
    "record file rotation": "Get record file rotation",
    "record split duration": "Get record split duration",
    "record frame indicator": "Get record frame indicator",
    "preroll enable": "Get preroll enable status",
    "preroll duration": "Get preroll duration",
    "mov format": "Get MOV format",
    "resolution": "Get resolution",
    "project fps": "Get project FPS",
    "vfr control": "Get variable frame rate control",
    "mov vfr": "Get MOV variable frame rate",
    "record fps": "Get record FPS",
    "photo quality": "Get photo quality",
    "photo capture": "Capture photo",
    "multiple cam mode": "Get multiple cam mode",
    "union auto exposure": "Get union auto exposure",
    "union auto white balance": "Get union auto white balance",
    "ezlink mode": "Get EZLink mode",
    "ezlink trigger": "Get EZLink trigger mode",
    "pixel link role": "Query pixel link role",
    "shutdown": "Shutdown",
    "reboot": "Reboot",
    "auto off": "Get auto off settings",
    "set auto off": "Set auto off",
    "auto standby": "Get auto standby settings",
    "set auto standby": "Set auto standby",
    "query timecode": "Query timecode",
    "reset timecode": "Reset timecode",
    "set current timecode": "Set current timecode",
    "set manual timecode": "Set manual timecode",
    "tc source": "Get timecode source",
    "tc count up": "Get timecode count up mode",
    "tc hdmi display": "Get HDMI timecode display",
    "tc drop frame option": "Get timecode drop frame option",
    "genlock status": "Get genlock status",
    "genlock coarse": "Get genlock coarse",
    "genlock fine": "Get genlock fine",
    "sync camera time": "Sync camera time",
    "set timezone": "Set timezone",
    "get date time": "Get date and time",
    "ntp time start": "Start NTP time sync",
    "ntp time stop": "Stop NTP time sync",
    "get ntp status": "Get NTP status",
    "set ntp interval": "Set NTP interval",
    "upload new firmware": "Upload new firmware",
    "refresh firmware": "Refresh firmware",
    "check firmware": "Check firmware",
    "ui check firmware": "UI check firmware",
    "batch get record settings": "Batch get record settings",
    "batch get video settings": "Batch get video settings",
    "batch get audio settings": "Batch get audio settings",
    "batch get image settings": "Batch get image settings",
    "batch get exposure settings": "Batch get exposure settings",
    "batch get white balance settings": "Batch get white balance settings",
    "batch get lens settings": "Batch get lens settings",
    "batch get assist tools settings": "Batch get assist tools settings",
    "batch get timecode settings": "Batch get timecode settings",
    "batch get multi camera settings": "Batch get multi camera settings",
    "batch get network settings": "Batch get network settings",
    "batch get security settings": "Batch get security settings",
    "batch get system settings": "Batch get system settings",
    "batch get maintenance settings": "Batch get maintenance settings",
    "video encoder": "Get video encoder",
    "bitrate level": "Get bitrate level",
    "compose mode WDR": "Get compose mode (WDR)",
    "eis on off": "Get electronic image stabilization on/off",
    "video rotation": "Get video rotation",
    "video timelapse interval": "Get video timelapse interval",
    "low jello": "Get low jello effect",
    "crop sensor": "Get crop sensor",
    "audio encoder": "Get audio encoder",
    "audio source": "Get audio source",
    "audio phantom power": "Get audio phantom power",
    "audio level display": "Get audio level display",
    "audio gain type": "Get audio gain type",
    "audio input level": "Get audio input level",
    "audio input gain": "Get audio input gain",
    "audio input left gain": "Get audio left channel input gain",
    "audio input right gain": "Get audio right channel input gain",
    "audio output gain": "Get audio output gain",
    "audio noise reduction": "Get audio noise reduction",
    "white balance mode": "Get white balance mode",
    "manual kelvin": "Get manual kelvin",
    "manual tint": "Get manual tint",
    "manual R": "Get manual red",
    "manual G": "Get manual green",
    "manual B": "Get manual blue",
    "auto white balance priority": "Get auto white balance priority",
    "lock awb in recording": "Get lock AWB in recording",
    "ev": "Get exposure value",
    "flicker": "Get flicker settings",
    "meter mode": "Get meter mode",
    "iris aperture": "Get iris aperture",
    "iso options": "Get ISO options",
    "min iso": "Get minimum ISO",
    "max iso": "Get maximum ISO",
    "iso control": "Get ISO control",
    "shutter angle control": "Get shutter angle control",
    "shutter operation": "Get shutter operation",
    "max exposure shutter time": "Get maximum exposure shutter time",
    "elec ND": "Get electronic ND",
    "auto exposure speed": "Get auto exposure speed",
    "black light comp": "Get black light compensation",
    "live ae shutter speed": "Get live AE shutter speed",
    "live ae shutter angle": "Get live AE shutter angle",
    "live ae iso": "Get live AE ISO",
    "ev choice": "Get exposure value choice",
    "shutter speed": "Get shutter speed",
    "shutter angle": "Get shutter angle",
    "lock ae in record": "Get lock AE in recording",
    "image profile": "Get image profile",
    "image noise reduction": "Get image noise reduction",
    "image luma level": "Get luma level",
    "image sharpness": "Get sharpness",
    "image brightness": "Get brightness",
    "image contrast": "Get contrast",
    "image saturation": "Get saturation",
    "image hue": "Get hue",
    "image dro": "Get dynamic range optimization",
    "image vignette": "Get vignette effect",
    "image matrix": "Query image matrix",
    "enable image matrix": "Enable image matrix",
    "set image matrix value": "set image matrix value",
    "cc option": "Query color correction options",
    "enable cc": "Enable color correction",
    "set cc hue": "Set color correction hue",
    "set cc saturation": "Set color correction saturation",
    "get gamma options": "Get gamma options",
    "set gamma power": "Set gamma power",
    "gamma black level": "Query black level",
    "config gamma black level": "Configure black level",
    "query black gamma": "Query black gamma",
    "config black gamma": "Configure black gamma",
    "gamma knee": "Query knee",
    "config gamma knee": "Configure knee",
    "get ip mode": "Get IP mode",
    "ethernet mode": "Get ethernet mode",
    "get ip configuration": "Get IP configuration",
    "DHCP router": "Set DHCP router mode",
    "Direct IP": "Set direct IP mode",
    "Static IP": "Set static IP",
    "query wifi status": "Query WiFi status",
    "get wifi options": "Get WiFi options",
    "set wifi options": "Set WiFi options",
    "get usb role": "Get USB role",
    "set usb role": "Set USB role",
    "query usb info": "Query USB information",
    "get sdi enable/disable": "Get SDI enable/disable",
    "set sdi enable/disable": "Set SDI enable/disable",
    "get sdi 3g mode": "Get SDI 3G mode",
    "set sdi 3g mode": "Set SDI 3G mode",
    "get hdmi format": "Get HDMI format",
    "set hdmi format": "Set HDMI format",
    "get hdmi osd option": "Get HDMI OSD option",
    "set hdmi osd option": "Set HDMI OSD option",
    "get hdmi osd layout": "Get HDMI OSD layout",
    "set hdmi osd layout": "Set HDMI OSD layout",
    "query free-D": "Query Free-D",
    "set free-D camera id": "Set Free-D camera ID",
    "config free-D": "Configure Free-D",
    "enable free-D": "Enable Free-D",
    "set visca id": "Set VISCA ID",
    "set visca baudrate": "Set VISCA baudrate",
    "enable visca": "Enable VISCA",
    "get send stream info": "Get send stream info",
    "send stream0": "Send stream source to Stream0",
    "send stream1": "Send stream source to Stream1",
    "stream0 settings": "Query stream0 settings",
    "stream1 settings": "Query stream1 settings",
    "change stream1 bitrate": "Change stream1 bitrate",
    "change stream1 width height": "Change stream1 width and height",
    "change stream1 encoder": "Change stream1 encoder",
    "change stream1 bitwidth": "Change stream1 bitwidth",
    "get streaming resolution": "Get stream resolution",
    "get streaming frame rate": "Get stream frame rate",
    "get streaming video encoder": "Get stream video encoder",
    "get streaming param save": "Get stream parameter save",
    "set streaming video encoder": "Set stream video encoder",
    "query rtmp": "Query RTMP",
    "query rtsp": "Query RTSP",
    "query ndi": "Query NDI",
    "query srt": "Query SRT",
    "disable restore lens pos": "Disable restore lens position",
    "enable restore lens pos": "Enable restore lens position",
    "get lens information": "Get lens information",
    "get lens focal length": "Get lens focal length",
    "lens focus near": "Focus near",
    "lens focus far": "Focus far",
    "lens focus stop": "Stop focus",
    "lens focus status": "Focus status",
    "trigger auto focus": "Trigger auto focus",
    "af speed": "Auto focus speed",
    "focus method": "Focus method",
    "continuous af": "Continuous auto focus",
    "af flexible size": "Flexible area size",
    "continuous af sensitivity": "Continuous auto focus sensitivity",
    "live continuous af": "Live continuous auto focus",
    "af adjust with PTZ": "AF adjust with PTZ",
    "MF assist preview": "Manual focus assist preview",
    "MF assist recording": "Manual focus assist recording",
    "trace with face id": "Trace with face ID",
    "af ROI type": "af ROI type",
    "update the ROI of af": "Update the ROI of af",
    "update the ROI of af to center": "Update the ROI of af to center",
    "get the ROI of af": "Get the ROI of af",
    "control the focus far/near": "Control the focus far/near",
    "get the focus position": "Get the focus position",
    "set the focus position": "Set the focus position",
    "zoom mode": "Zoom mode",
    "zoom position": "Zoom position",
    "zoom status": "Zoom status",
    "zoom in with speed": "Zoom in with speed",
    "zoom out": "Zoom out",
    "stop zoom": "Stop zoom",
    "zoom to a position": "Zoom to a position",
    "pan tilt direction": "Pan tilt direction control",
    "query pan tilt": "Query PTZ",
    "query pan tilt details": "Query PTZ details",
    "stop pan tilt": "Stop PTZ",
    "stop all pan tilt": "Stop all PTZ",
    "pan tilt direction move": "Direction move",
    "pan tilt speed": "Pan and tilt speed",
    "pan tilt home": "pan tilt home",
    "pan tilt reset": "pan tilt reset",
    "pan tilt limit update": "Limit update",
    "pan tilt limit": "pan tilt limit",
    "pan tilt speed mode": "Speed mode",
    "pan tilt speed with zoom position": "Speed with zoom position",
    "pan tilt flip": "Flip",
    "pan tilt privacy mode": "Privacy mode",
    "pan tilt power on position": "Power on position",
    "PTZ preset recall": "PTZ preset recall",
    "PTZ preset save": "PTZ preset save",
    "PTZ preset delete": "PTZ preset delete",
    "PTZ preset info": "PTZ preset info",
    "PTZ preset name": "PTZ preset name",
    "PTZ preset speed unit": "PTZ preset speed unit",
    "PTZ preset speed by duration": "PTZ preset speed by duration",
    "PTZ preset speed by index": "PTZ preset speed by index",
    "PTZ common speed": "PTZ common speed",
    "PTZ common time": "PTZ common time",
    "PTZ preset recall mode": "PTZ preset recall mode",
    "PTZ recall speed mode": "PTZ recall speed mode",
    "PTZ freeze duration recall": "PTZ freeze duration during recall",
    "PTZ common speed unit": "PTZ common speed unit",
    "delete ptz trace": "Delete PTZ trace",
    "rename ptz trace": "Rename PTZ trace",
    "record ptz trace start": "Record ptz trace start",
    "record ptz trace stop": "Record ptz trace stop",
    "prepare play ptz trace": "Prepare play ptz trace",
    "play ptz trace start": "Play ptz trace start",
    "play ptz trace stop": "Play ptz trace stop",
    "query ptz trace": "Query ptz trace",
    "get ptz trace info": "Get ptz trace info",
    "check card present": "Check if card is present",
    "query card format": "Query card format",
    "format storage card": "Format storage card",
    "format to fat32": "Format storage card to FAT32",
    "format to exfat": "Format storage card to exFAT",
    "query card free space": "Query card free space",
    "query card total space": "Query card total space",
    "list card folders": "List folders in storage card",
    "list files in card folders": "List files in card folder",
    "download file from card": "Download file from storage card",
    "delete file in card": "Delete file in storage card",
    "get file thumbnail": "Get file thumbnail",
    "get file screen nail": "Get file screen nail",
    "get file create time": "Get file creation time",
    "get file info": "Get file information"
  }
};

// 获取命令描述的函数
function getCommandDescription(key, lang = 'en') {
  const descriptions = commandDescriptions[lang] || commandDescriptions.en;
  return descriptions[key] || key;
}

// 动态获取当前语言的命令描述
function getCurrentCommandDescription(key) {
  // 从HTML页面获取当前语言
  const currentLang = document.documentElement.lang || 'en';
  return getCommandDescription(key, currentLang);
}

const commands = [
  // ===== Camera Utility =====
  { key: "camera info", url: "/info", category: "utility", description: "" },
  { key: "camera sn", url: "/ctrl/get?k=sn", category: "utility", description: "" },
  { key: "commit info", url: "/commit_info", category: "utility", description: "" },
  { key: "nick name", url: "/ctrl/nick_name", category: "utility", description: "" },
  { key: "camera status", url: "/camera_status", category: "utility", description: "" },
  { key: "check session status", url: "/ctrl/session", category: "utility", description: "" },
  { key: "occupy the session", url: "/ctrl/session?action=occupy", category: "utility", description: "" },
  { key: "quit the session", url: "/ctrl/session?action=quit", category: "utility", description: "" },
  { key: "clear setting", url: "/ctrl/set?action=clear", category: "utility", description: "" },
  { key: "temperature", url: "/ctrl/temperature", category: "utility", description: "" },
  { key: "battery_voltage", url: "/ctrl/get?k=battery_voltage", category: "utility", description: "" },
  { key: "battery", url: "/ctrl/get?k=battery", category: "utility", description: "" },
  { key: "raw over hdmi", url: "/ctrl/get?k=raw_over_hdmi", category: "utility", description: "" },
  { key: "led on/off", url: "/ctrl/get?k=led", category: "utility", description: "" },
  { key: "desqueeze", url: "/ctrl/get?k=desqueeze", category: "utility", description: "" },
  { key: "export profile", url: "/prf/export", category: "utility", description: "" },

  // ===== Work Mode =====
  { key: "working mode", url: "/ctrl/mode?action=query", category: "work_mode", description: "" },
  { key: "to record mode", url: "/ctrl/mode?action=to_rec", category: "work_mode", description: "" },
  { key: "to playback mode", url: "/ctrl/mode?action=to_pb", category: "work_mode", description: "" },
  { key: "to standby", url: "/ctrl/mode?action=to_standby", category: "work_mode", description: "" },
  { key: "exit standby", url: "/ctrl/mode?action=exit_standby", category: "work_mode", description: "" },

  // ===== Record =====
  { key: "record mode", url: "/ctrl/get?k=record_mode", category: "record", description: "" },
  { key: "start record", url: "/ctrl/rec?action=start", category: "record", description: "" },
  { key: "stop record", url: "/ctrl/rec?action=stop", category: "record", description: "" },
  { key: "get record status", url: "/ctrl/rec?action=query", category: "record", description: "" },
  { key: "get recording duration", url: "/ctrl/get?k=rec_duration", category: "record", description: "" },
  { key: "remain recording time", url: "/ctrl/rec?action=remain", category: "record", description: "" },
  { key: "repair status", url: "/ctrl/rec?action=query_repairing", category: "record", description: "" },
  { key: "set record meta", url: "/ctrl/set?record_meta=$value", category: "record", description: "" },
  { key: "get record meta option", url: "/ctrl/get?k=record_meta", category: "record", description: "" },
  { key: "get camera id", url: "/ctrl/get?k=camera_id", category: "record", description: "" },
  { key: "set camera id", url: "/ctrl/set?camera_id=$value", category: "record", description: "" },
  { key: "get reel name", url: "/ctrl/get?k=reelname", category: "record", description: "" },
  { key: "set reel name", url: "/ctrl/set?reelname=$value", category: "record", description: "" },
  { key: "record format", url: "/ctrl/get?k=record_file_format", category: "record", description: "" },
  { key: "record file rotation", url: "/ctrl/get?k=rotation", category: "record", description: "" },
  { key: "record split duration", url: "/ctrl/get?k=split_duration", category: "record", description: "" },
  { key: "record frame indicator", url: "/ctrl/get?k=rec_frame_indicator", category: "record", description: "" },
  { key: "preroll enable", url: "/ctrl/get?k=preroll", category: "record", description: "" },
  { key: "preroll duration", url: "/ctrl/get?k=preroll_duration", category: "record", description: "" },

  // ===== Camera Shot =====
  { key: "mov format", url: "/ctrl/get?k=movfmt", category: "camera_shot", description: "" },
  { key: "resolution", url: "/ctrl/get?k=resolution", category: "camera_shot", description: "" },
  { key: "project fps", url: "/ctrl/get?k=project_fps", category: "camera_shot", description: "" },
  { key: "vfr control", url: "/ctrl/get?k=vfr_ctrl", category: "camera_shot", description: "" },
  { key: "mov vfr", url: "/ctrl/get?k=movvfr", category: "camera_shot", description: "" },
  { key: "record fps", url: "/ctrl/get?k=rec_fps", category: "camera_shot", description: "" },

  // ===== Photo =====
  { key: "photo quality", url: "/ctrl/get?k=photo_q", category: "photo", description: "" },
  { key: "photo capture", url: "/ctrl/still?action=cap", category: "photo", description: "" },

  // ===== Multi Cam =====
  { key: "multiple cam mode", url: "/ctrl/get?k=multiple_mode", category: "multi_cam", description: "" },
  { key: "union auto exposure", url: "/ctrl/get?k=union_ae", category: "multi_cam", description: "" },
  { key: "union auto white balance", url: "/ctrl/get?k=union_awb", category: "multi_cam", description: "" },
  { key: "ezlink mode", url: "/ctrl/get?k=ezlink_mode", category: "multi_cam", description: "" },
  { key: "ezlink trigger", url: "/ctrl/get?k=ezlink_trigger", category: "multi_cam", description: "" },
  { key: "pixel link role", url: "/info", category: "multi_cam", description: "" },

  // ===== Power =====
  { key: "shutdown", url: "/ctrl/shutdown", category: "power", description: "" },
  { key: "reboot", url: "/ctrl/reboot", category: "power", description: "" },
  { key: "auto off", url: "/ctrl/get?k=auto_off", category: "power", description: "" },
  { key: "set auto off", url: "/ctrl/set?auto_off=$value", category: "power", description: "" },
  { key: "auto standby", url: "/ctrl/get?k=auto_standby", category: "power", description: "" },
  { key: "set auto standby", url: "/ctrl/set?auto_standby=$value", category: "power", description: "" },

  // ===== Time Code =====
  { key: "query timecode", url: "/ctrl/tc?action=query", category: "timecode", description: "" },
  { key: "reset timecode", url: "/ctrl/tc?action=reset", category: "timecode", description: "" },
  { key: "set current timecode", url: "/ctrl/tc?action=current_time", category: "timecode", description: "" },
  { key: "set manual timecode", url: "/ctrl/tc?action=set&tc=$tc_value", category: "timecode", description: "" },
  { key: "tc source", url: "/ctrl/get?k=tc_source", category: "timecode", description: "" },
  { key: "tc count up", url: "/ctrl/get?k=tc_count_up", category: "timecode", description: "" },
  { key: "tc hdmi display", url: "/ctrl/get?k=tc_hdmi_display", category: "timecode", description: "" },
  { key: "tc drop frame option", url: "/ctrl/get?k=tc_drop_frame", category: "timecode", description: "" },

  // ===== Genlock =====
  { key: "genlock status", url: "/ctrl/get?k=genlock", category: "genlock", description: "" },
  { key: "genlock coarse", url: "/ctrl/get?k=genlock_coarse", category: "genlock", description: "" },
  { key: "genlock fine", url: "/ctrl/get?k=genlock_fine", category: "genlock", description: "" },

  // ===== Clock =====
  { key: "sync camera time", url: "/datetime?date=YYYY-MM-DD&time=hh:mm:ss", category: "clock", description: "" },
  { key: "set timezone", url: "/datetime?timezone=$timezone_value", category: "clock", description: "" },
  { key: "get date time", url: "/datetime/get", category: "clock", description: "" },
  { key: "ntp time start", url: "/ctrl/sntp?action=start&ip_addr=192.aa.bb.cc&port=123&interval=24", category: "clock", description: "" },
  { key: "ntp time stop", url: "/ctrl/sntp?action=stop", category: "clock", description: "" },
  { key: "get ntp status", url: "/ctrl/sntp?action=get", category: "clock", description: "" },
  { key: "set ntp interval", url: "/ctrl/sntp?action=set_interval&interval=$interval_value", category: "clock", description: "" },

  // ===== Upgrade =====
  { key: "upload new firmware", url: "/uploadfirmware", category: "upgrade", description: "" },
  { key: "refresh firmware", url: "/ctrl/upgrade?action=run", category: "upgrade", description: "" },
  { key: "check firmware", url: "/ctrl/upgrade?action=fw_check", category: "upgrade", description: "" },
  { key: "ui check firmware", url: "/ctrl/upgrade?action=ui_check", category: "upgrade", description: "" },

  // ===== Batch Catalog Settings Query =====
  { key: "batch get record settings", url: "/ctrl/getbatch?catalog=record", category: "batch_query", description: "" },
  { key: "batch get video settings", url: "/ctrl/getbatch?catalog=video", category: "batch_query", description: "" },
  { key: "batch get audio settings", url: "/ctrl/getbatch?catalog=audio", category: "batch_query", description: "" },
  { key: "batch get image settings", url: "/ctrl/getbatch?catalog=image", category: "batch_query", description: "" },
  { key: "batch get exposure settings", url: "/ctrl/getbatch?catalog=exposure", category: "batch_query", description: "" },
  { key: "batch get white balance settings", url: "/ctrl/getbatch?catalog=wb", category: "batch_query", description: "" },
  { key: "batch get lens settings", url: "/ctrl/getbatch?catalog=lens", category: "batch_query", description: "" },
  { key: "batch get assist tools settings", url: "/ctrl/getbatch?catalog=assitool", category: "batch_query", description: "" },
  { key: "batch get timecode settings", url: "/ctrl/getbatch?catalog=timecode", category: "batch_query", description: "" },
  { key: "batch get multi camera settings", url: "/ctrl/getbatch?catalog=multicam", category: "batch_query", description: "" },
  { key: "batch get network settings", url: "/ctrl/getbatch?catalog=network", category: "batch_query", description: "" },
  { key: "batch get security settings", url: "/ctrl/getbatch?catalog=security", category: "batch_query", description: "" },
  { key: "batch get system settings", url: "/ctrl/getbatch?catalog=system", category: "batch_query", description: "" },
  { key: "batch get maintenance settings", url: "/ctrl/getbatch?catalog=maintanence", category: "batch_query", description: "" },

  // ===== Video Settings =====
  { key: "video encoder", url: "/ctrl/get?k=video_encoder", category: "video", description: "" },
  { key: "mov format", url: "/ctrl/get?k=movfmt", category: "video", description: "" },
  { key: "bitrate level", url: "/ctrl/get?k=bitrate_level", category: "video", description: "" },
  { key: "compose mode WDR", url: "/ctrl/get?k=compose_mode", category: "video", description: "" },
  { key: "eis on off", url: "/ctrl/get?k=eis_on_off", category: "video", description: "" },
  { key: "video rotation", url: "/ctrl/get?k=vid_rot", category: "video", description: "" },
  { key: "video timelapse interval", url: "/ctrl/get?k=video_tl_interval", category: "video", description: "" },
  { key: "low jello", url: "/ctrl/get?k=low_jello", category: "video", description: "" },
  { key: "crop sensor", url: "/ctrl/get?k=crop_sensor", category: "video", description: "" },

  // ===== Audio Settings =====
  { key: "audio encoder", url: "/ctrl/get?k=primary_audio", category: "audio", description: "" },
  { key: "audio source", url: "/ctrl/get?k=audio_channel", category: "audio", description: "" },
  { key: "audio phantom power", url: "/ctrl/get?k=audio_phantom_power", category: "audio", description: "" },
  { key: "audio level display", url: "/ctrl/get?k=audio_level_display", category: "audio", description: "" },
  { key: "audio gain type", url: "/ctrl/get?k=ain_gain_type", category: "audio", description: "" },
  { key: "audio input level", url: "/ctrl/get?k=audio_input_level", category: "audio", description: "" },
  { key: "audio input gain", url: "/ctrl/get?k=audio_input_gain", category: "audio", description: "" },
  { key: "audio input left gain", url: "/ctrl/get?k=audio_in_l_gain", category: "audio", description: "" },
  { key: "audio input right gain", url: "/ctrl/get?k=audio_in_r_gain", category: "audio", description: "" },
  { key: "audio output gain", url: "/ctrl/get?k=audio_output_gain", category: "audio", description: "" },
  { key: "audio noise reduction", url: "/ctrl/get?k=audio_noise_reduction", category: "audio", description: "" },

  // ===== White Balance Settings =====
  { key: "white balance mode", url: "/ctrl/get?k=wb", category: "white_balance", description: "" },
  { key: "manual kelvin", url: "/ctrl/get?k=mwb", category: "white_balance", description: "" },
  { key: "manual tint", url: "/ctrl/get?k=tint", category: "white_balance", description: "" },
  { key: "manual R", url: "/ctrl/get?k=mwb_r", category: "white_balance", description: "" },
  { key: "manual G", url: "/ctrl/get?k=mwb_g", category: "white_balance", description: "" },
  { key: "manual B", url: "/ctrl/get?k=mwb_b", category: "white_balance", description: "" },
  { key: "auto white balance priority", url: "/ctrl/get?k=wb_priority", category: "white_balance", description: "" },
  { key: "lock awb in recording", url: "/ctrl/get?k=lock_awb_in_rec", category: "white_balance", description: "" },

  // ===== Exposure Settings =====
  { key: "ev", url: "/ctrl/get?k=ev", category: "exposure", description: "" },
  { key: "flicker", url: "/ctrl/get?k=flicker", category: "exposure", description: "" },
  { key: "meter mode", url: "/ctrl/get?k=meter_mode", category: "exposure", description: "" },
  { key: "iris aperture", url: "/ctrl/get?k=iris", category: "exposure", description: "" },
  { key: "iris aperture2", url: "/ctrl/get?k=live_ae_fno", category: "exposure", description: "" },
  { key: "iso options", url: "/ctrl/get?k=iso", category: "exposure", description: "" },
  { key: "min iso", url: "/ctrl/get?k=min_iso", category: "exposure", description: "" },
  { key: "max iso", url: "/ctrl/get?k=max_iso", category: "exposure", description: "" },
  { key: "iso control", url: "/ctrl/get?k=iso_ctrl", category: "exposure", description: "" },
  { key: "shutter angle ctrl", url: "/ctrl/get?k=shutter_angle_ctrl", category: "exposure", description: "" },
  { key: "shutter operation", url: "/ctrl/get?k=sht_operation", category: "exposure", description: "" },
  { key: "max exposure shutter time", url: "/ctrl/get?k=max_exp_shutter_time", category: "exposure", description: "" },
  { key: "elec ND", url: "/ctrl/get?k=eND", category: "exposure", description: "" },
  { key: "auto exposure speed", url: "/ctrl/get?k=ae_speed", category: "exposure", description: "" },
  { key: "black light comp", url: "/ctrl/get?k=bl_comp", category: "exposure", description: "" },
  { key: "live ae shutter speed", url: "/ctrl/get?k=live_ae_shutter", category: "exposure", description: "" },
  { key: "live ae shutter angle", url: "/ctrl/get?k=live_ae_shutter_angle", category: "exposure", description: "" },
  { key: "live ae iso", url: "/ctrl/get?k=live_ae_iso", category: "exposure", description: "" },
  { key: "ev choice", url: "/ctrl/get?k=ev_choice", category: "exposure", description: "" },
  { key: "shutter time", url: "/ctrl/get?k=shutter_time", category: "exposure", description: "" },
  { key: "shutter angle", url: "/ctrl/get?k=shutter_angle", category: "exposure", description: "" },
  { key: "lock ae in record", url: "/ctrl/get?k=lock_ae_in_rec", category: "exposure", description: "" },

  // ===== Image Basic Settings =====
  { key: "image profile", url: "/ctrl/get?k=lut", category: "image", description: "" },
  { key: "image noise reduction", url: "/ctrl/get?k=noise_reduction", category: "image", description: "" },
  { key: "image luma level", url: "/ctrl/get?k=luma_level", category: "image", description: "" },
  { key: "image sharpness", url: "/ctrl/get?k=sharpness", category: "image", description: "" },
  { key: "image brightness", url: "/ctrl/get?k=brightness", category: "image", description: "" },
  { key: "image contrast", url: "/ctrl/get?k=contrast", category: "image", description: "" },
  { key: "image saturation", url: "/ctrl/get?k=saturation", category: "image", description: "" },
  { key: "image hue", url: "/ctrl/get?k=hue", category: "image", description: "" },
  { key: "image dro", url: "/ctrl/get?k=dro", category: "image", description: "" },
  { key: "image vignette", url: "/ctrl/get?k=vignette", category: "image", description: "" },

  // ===== Image Matrix =====
  { key: "image matrix", url: "/ctrl/matrix", category: "image_matrix", description: "" },
  { key: "enable image matrix", url: "/ctrl/matrix?enable=$value", category: "image_matrix", description: "" },
  { key: "set image matrix value", url: "/ctrl/matrix?index=$index_value&value=$params", category: "image_matrix", description: "" },

  // ===== Image Color Correction =====
  { key: "cc option", url: "/ctrl/cc", category: "color_correction", description: "" },
  { key: "enable cc", url: "/ctrl/cc?enable=$value", category: "color_correction", description: "" },
  { key: "set cc hue", url: "/ctrl/cc?action=set_hue&index=$index_value&value=$params", category: "color_correction", description: "" },
  { key: "set cc saturation", url: "/ctrl/cc?action=set_sat&index=$index_value&value=$params", category: "color_correction", description: "" },

  // ===== Image Gamma Setting =====
  { key: "get gamma options", url: "/ctrl/gamma?action=get&option=gamma", category: "gamma", description: "" },
  { key: "set gamma power", url: "/ctrl/gamma?action=set&option=gamma&base=$base_value&power=$power_value", category: "gamma", description: "" },
  { key: "gamma black level", url: "/ctrl/gamma?action=get&option=black_level", category: "gamma", description: "" },
  { key: "config gamma black level", url: "/ctrl/gamma?action=set&option=black_level&enable=1&level=10", category: "gamma", description: "" },
  { key: "query black gamma", url: "/ctrl/gamma?action=get&option=black_gamma", category: "gamma", description: "" },
  { key: "config black gamma", url: "/ctrl/gamma?action=set&option=black_gamma&enable=1&range=Narrow&level=0", category: "gamma", description: "" },
  { key: "gamma knee", url: "/ctrl/gamma?action=get&option=knee", category: "gamma", description: "" },
  { key: "config gamma knee", url: "/ctrl/gamma?action=set&option=knee&enable=1&point=50&slope=0", category: "gamma", description: "" },

  // ===== Network Settings =====
  { key: "get ip mode", url: "/ctrl/network?action=query", category: "network", description: "" },
  { key: "ethernet mode", url: "/ctrl/get?k=eth_mode", category: "network", description: "" },
  { key: "get ip configuration", url: "/ctrl/network?action=info", category: "network", description: "" },
  { key: "DHCP router", url: "/ctrl/network?action=set&mode=Router", category: "network", description: "" },
  { key: "Direct IP", url: "/ctrl/network?action=set&mode=Direct", category: "network", description: "" },
  { key: "Static IP", url: "/ctrl/network?action=set&mode=Static&ipaddr=192.168.1.100&netmask=255.255.255.0&gateway=192.168.1.1&dns=8.8.8.8", category: "network", description: "" },
  { key: "query wifi status", url: "/ctrl/wifi_ctrl?action=query", category: "network", description: "" },
  { key: "get wifi options", url: "/ctrl/get?k=wifi", category: "network", description: "" },
  { key: "set wifi options", url: "/ctrl/set?wifi=$value", category: "network", description: "" },

  // ===== Connection Settings =====
  { key: "get usb role", url: "/ctrl/get?k=usb_device_role", category: "connection", description: "" },
  { key: "set usb role", url: "/ctrl/set?usb_device_role=$value", category: "connection", description: "" },
  { key: "query usb info", url: "/ctrl/usb?action=query", category: "connection", description: "" },
  { key: "get sdi enable/disable", url: "/ctrl/get?k=sdi", category: "connection", description: "" },
  { key: "set sdi enable/disable", url: "/ctrl/set?sdi=$value", category: "connection", description: "" },
  { key: "get sdi 3g mode", url: "/ctrl/get?k=3g_sdi_mode", category: "connection", description: "" },
  { key: "set sdi 3g mode", url: "/ctrl/set?3g_sdi_mode=$value", category: "connection", description: "" },
  { key: "get hdmi format", url: "/ctrl/get?k=hdmi_format", category: "connection", description: "" },
  { key: "set hdmi format", url: "/ctrl/set?hdmi_format=$value", category: "connection", description: "" },
  { key: "get hdmi osd option", url: "/ctrl/get?k=hdmi_osd", category: "connection", description: "" },
  { key: "set hdmi osd option", url: "/ctrl/set?hdmi_osd=$value", category: "connection", description: "" },
  { key: "get hdmi osd layout", url: "/ctrl/get?k=osd_layout", category: "connection", description: "" },
  { key: "set hdmi osd layout", url: "/ctrl/set?osd_layout=$value", category: "connection", description: "" },
  { key: "query free-D", url: "/ctrl/freed", category: "connection", description: "" },
  { key: "set free-D camera id", url: "/ctrl/freed?camera_id=$value", category: "connection", description: "" },
  { key: "config free-D", url: "/ctrl/freed?ip=$ip_address_value&port=$port_value", category: "connection", description: "" },
  { key: "enable free-D", url: "/ctrl/freed?enable=$value", category: "connection", description: "" },
  { key: "set visca id", url: "/ctrl/set?visca_id=$id_value", category: "connection", description: "" },
  { key: "set visca baudrate", url: "/ctrl/set?visca_baudrate=$value", category: "connection", description: "" },
  { key: "enable visca", url: "/ctrl/set?visca_enable=$value", category: "connection", description: "" },

  // ===== Streaming =====
  { key: "get send stream info", url: "/ctrl/get?k=send_stream", category: "streaming", description: "" },
  { key: "send stream0", url: "/ctrl/set?send_stream=Stream0", category: "streaming", description: "" },
  { key: "send stream1", url: "/ctrl/set?send_stream=Stream1", category: "streaming", description: "" },
  { key: "stream0 settings", url: "/ctrl/stream_setting?index=stream0&action=query", category: "streaming", description: "" },
  { key: "stream1 settings", url: "/ctrl/stream_setting?index=stream1&action=query", category: "streaming", description: "" },
  { key: "change stream1 bitrate", url: "/ctrl/stream_setting?index=stream1&bitrate=2000000", category: "streaming", description: "" },
  { key: "change stream1 width height", url: "/ctrl/stream_setting?index=stream1&width=1920&height=1080", category: "streaming", description: "" },
  { key: "change stream1 encoder", url: "/ctrl/stream_setting?index=stream1&venc=h265", category: "streaming", description: "" },
  { key: "change stream1 bitwidth", url: "/ctrl/stream_setting?index=stream1&bitwidth=8", category: "streaming", description: "" },
  { key: "get streaming resolution", url: "/ctrl/get?k=stream_resolution", category: "streaming", description: "" },
  { key: "get streaming frame rate", url: "/ctrl/get?k=stream_fps", category: "streaming", description: "" },
  { key: "get streaming video encoder", url: "/ctrl/get?k=stream_video_encoder", category: "streaming", description: "" },
  { key: "get streaming param save", url: "/ctrl/get?k=stream_param_save", category: "streaming", description: "" },
  { key: "set streaming video encoder", url: "/ctrl/set?stream_video_encoder=H.265", category: "streaming", description: "" },
  { key: "query rtmp", url: "/ctrl/rtmp?action=query", category: "streaming", description: "" },
  { key: "query rtsp", url: "/ctrl/rtsp?action=query", category: "streaming", description: "" },
  { key: "query ndi", url: "/ctrl/ndi?action=query", category: "streaming", description: "" },
  { key: "query srt", url: "/ctrl/srt?action=query", category: "streaming", description: "" },

  // ===== Lens Control =====
  { key: "disable restore lens pos", url: "/ctrl/set?restore_lens_pos=Disable", category: "lens", description: "" },
  { key: "enable restore lens pos", url: "/ctrl/set?restore_lens_pos=Enable", category: "lens", description: "" },
  { key: "get lens information", url: "/ctrl/lens?action=query", category: "lens", description: "" },
  { key: "get lens focal length", url: "/ctrl/get?k=lens_focal_length", category: "lens", description: "" },

  // ===== Focus =====
  { key: "lens focus near", url: "/ctrl/lens?action=focusnear&fspeed=$speed_value", category: "focus", description: "" },
  { key: "lens focus far", url: "/ctrl/lens?action=focusfar&fspeed=$speed_value", category: "focus", description: "" },
  { key: "lens focus stop", url: "/ctrl/lens?action=focusstop", category: "focus", description: "" },
  { key: "lens focus status", url: "/ctrl/lens?action=f_status", category: "focus", description: "" },
  { key: "trigger auto focus", url: "/ctrl/af", category: "focus", description: "" },
  { key: "af speed", url: "/ctrl/get?k=af_speed", category: "focus", description: "" },
  { key: "focus method", url: "/ctrl/get?k=focus", category: "focus", description: "" },
  { key: "continuous af", url: "/ctrl/get?k=caf", category: "focus", description: "" },
  { key: "af flexible size", url: "/ctrl/get?k=af_area", category: "focus", description: "" },
  { key: "continuous af sensitivity", url: "/ctrl/get?k=caf_sens", category: "focus", description: "" },
  { key: "live continuous af", url: "/ctrl/get?k=live_caf", category: "focus", description: "" },
  { key: "af adjust with PTZ", url: "/ctrl/get?k=af_adjust_with_ptz", category: "focus", description: "" },
  { key: "MF assist preview", url: "/ctrl/get?k=mf_mag", category: "focus", description: "" },
  { key: "MF assist recording", url: "/ctrl/get?k=mf_recording", category: "focus", description: "" },
  { key: "trace with face id", url: "/ctrl/af_face/trace_target?id=$id_value", category: "focus", description: "" },
  { key: "af ROI type", url: "/ctrl/get?k=af_mode", category: "focus", description: "" },
  { key: "update the ROI of af", url: "/ctrl/af?action=update_roi&x=0&y=0&w=100&h=100", category: "focus", description: "" },
  { key: "update the ROI of af to center", url: "/ctrl/af?action=update_roi_center&x=500&y=500", category: "focus", description: "" },
  { key: "get the ROI of af", url: "/ctrl/af?action=query", category: "focus", description: "" },
  { key: "control the focus far/near", url: "/ctrl/set?mf_drive=1、2、3、-3、-2、-1", category: "focus", description: "" },
  { key: "get the focus position", url: "/ctrl/get?k=lens_focus_pos", category: "focus", description: "" },
  { key: "set the focus position", url: "/ctrl/set?lens_focus_pos=$value", category: "focus", description: "" },

  // ===== Zoom =====
  { key: "zoom mode", url: "/ctrl/get?k=zoom_mode", category: "zoom", description: "" },
  { key: "zoom position", url: "/ctrl/get?k=lens_zoom_pos", category: "zoom", description: "" },
  { key: "zoom status", url: "/ctrl/lens?action=z_status", category: "zoom", description: "" },
  { key: "zoom in with speed", url: "/ctrl/set?lens_zoom=in&fspeed=$speed_value", category: "zoom", description: "" },
  { key: "zoom out", url: "/ctrl/set?lens_zoom=out&fspeed=$speed_value", category: "zoom", description: "" },
  { key: "stop zoom", url: "/ctrl/set?lens_zoom=stop", category: "zoom", description: "" },
  { key: "zoom to a position", url: "/ctrl/set?lens_zoom_pos=value", category: "zoom", description: "" },

  // ===== Pan Tilt Control =====
  { key: "pan tilt direction", url: "/ctrl/pt?action=direction&speed=N", category: "ptz", description: "" },
  { key: "query pan tilt", url: "/ctrl/pt?action=query", category: "ptz", description: "" },
  { key: "query pan tilt details", url: "/ctrl/pt?action=query&detail=y", category: "ptz", description: "" },
  { key: "stop pan tilt", url: "/ctrl/pt?action=stop", category: "ptz", description: "" },
  { key: "stop all pan tilt", url: "/ctrl/pt?action=stop_all", category: "ptz", description: "" },
  { key: "pan tilt direction move", url: "/ctrl/pt?action=$direction&fspeed=$speed_value", category: "ptz", description: "" },
  { key: "pan tilt speed", url: "/ctrl/pt?action=pt&pan_speed=$pan_speed_value&tilt_speed=$tilt_speed_value", category: "ptz", description: "" },
  { key: "pan tilt home", url: "/ctrl/pt?action=home", category: "ptz", description: "" },
  { key: "pan tilt reset", url: "/ctrl/pt?action=reset", category: "ptz", description: "" },
  { key: "pan tilt limit update", url: "/ctrl/pt?action=limit&direct=$direct_value&pan_pos=$pan_pos_value&tilt_pos=$tilt_pos_value", category: "ptz", description: "" },
  { key: "pan tilt limit", url: "/ctrl/get?k=ptz_limit", category: "ptz", description: "" },
  { key: "pan tilt speed mode", url: "/ctrl/get?k=pt_speedmode", category: "ptz", description: "" },
  { key: "pan tilt speed with zoom position", url: "/ctrl/get?k=pt_speed_with_zoom_pos", category: "ptz", description: "" },
  { key: "pan tilt flip", url: "/ctrl/get?k=ptz_flip", category: "ptz", description: "" },
  { key: "pan tilt privacy mode", url: "/ctrl/get?k=pt_priv_mode", category: "ptz", description: "" },
  { key: "pan tilt power on position", url: "/ctrl/get?k=pt_pwr_pos", category: "ptz", description: "" },

  // ===== PTZ Preset =====
  { key: "PTZ preset recall", url: "/ctrl/preset?action=recall&index=$value", category: "ptz_preset", description: "" },
  { key: "PTZ preset save", url: "/ctrl/preset?action=save&index=$value", category: "ptz_preset", description: "" },
  { key: "PTZ preset delete", url: "/ctrl/preset?action=del&index=$value", category: "ptz_preset", description: "" },
  { key: "PTZ preset info", url: "/ctrl/preset?action=get_info&index=$index_value", category: "ptz_preset", description: "" },
  { key: "PTZ preset name", url: "/ctrl/preset?action=set_name&index=$value&new_name=$name_vaule", category: "ptz_preset", description: "" },
  { key: "PTZ preset speed unit", url: "/ctrl/preset?action=preset_speed&index=$index_value&preset_speed_unit=$unit_value", category: "ptz_preset", description: "" },
  { key: "PTZ preset speed by duration", url: "/ctrl/preset?action=preset_speed&index=$index_value&preset_time=$time_value", category: "ptz_preset", description: "" },
  { key: "PTZ preset speed by index", url: "/ctrl/preset?action=preset_speed&index=$index_value&preset_speed=$speed_value", category: "ptz_preset", description: "" },
  { key: "PTZ common speed", url: "/ctrl/get?k=ptz_common_speed", category: "ptz_preset", description: "" },
  { key: "PTZ common time", url: "/ctrl/get?k=ptz_common_time", category: "ptz_preset", description: "" },
  { key: "PTZ preset recall mode", url: "/ctrl/get?k=ptz_preset_mode", category: "ptz_preset", description: "" },
  { key: "PTZ recall speed mode", url: "/ctrl/get?k=ptz_speed_mode", category: "ptz_preset", description: "" },
  { key: "PTZ freeze duration recall", url: "/ctrl/get?k=freeze_during_preset", category: "ptz_preset", description: "" },
  { key: "PTZ common speed unit", url: "/ctrl/get?k=ptz_common_speed_unit", category: "ptz_preset", description: "" },

  // ===== PTZ Trace =====
  { key: "delete ptz trace", url: "/ctrl/ptrace?action=del&index=$index_value", category: "ptz_trace", description: "" },
  { key: "rename ptz trace", url: "/ctrl/ptrace?action=set_name&index=$index_value&new_name=$new_name_value", category: "ptz_trace", description: "" },
  { key: "record ptz trace start", url: "/ctrl/ptrace?action=rec_start&index=$index_value", category: "ptz_trace", description: "" },
  { key: "record ptz trace stop", url: "/ctrl/ptrace?action=rec_stop", category: "ptz_trace", description: "" },
  { key: "prepare play ptz trace", url: "/ctrl/ptrace?action=play_prepare&index=$index_value", category: "ptz_trace", description: "" },
  { key: "play ptz trace start", url: "/ctrl/ptrace?action=play_start", category: "ptz_trace", description: "" },
  { key: "play ptz trace stop", url: "/ctrl/ptrace?action=play_stop", category: "ptz_trace", description: "" },
  { key: "query ptz trace", url: "/ctrl/ptrace?action=query", category: "ptz_trace", description: "" },
  { key: "get ptz trace info", url: "/ctrl/ptrace?action=get_info&index=$index_value", category: "ptz_trace", description: "" },

  // ===== Storage =====
  { key: "check card present", url: "/ctrl/card?action=present", category: "storage", description: "" },
  { key: "query card format", url: "/ctrl/card?action=query_format", category: "storage", description: "" },
  { key: "format storage card", url: "/ctrl/card?action=format", category: "storage", description: "" },
  { key: "format to fat32", url: "/ctrl/card?action=fat32", category: "storage", description: "" },
  { key: "format to exfat", url: "/ctrl/card?action=exfat", category: "storage", description: "" },
  { key: "query card free space", url: "/ctrl/card?action=query_free", category: "storage", description: "" },
  { key: "query card total space", url: "/ctrl/card?action=query_total", category: "storage", description: "" },
  { key: "list card folders", url: "/DCIM/", category: "storage", description: "" },
  { key: "list files in card folders", url: "/DCIM/$folderName", category: "storage", description: "" },
  { key: "download file from card", url: "/DCIM/$folderName/$fileName", category: "storage", description: "" },
  { key: "delete file in card", url: "/DCIM/$folderName/$fileName?act=rm", category: "storage", description: "" },
  { key: "get file thumbnail", url: "/DCIM/$folderName/$fileName?act=thm", category: "storage", description: "" },
  { key: "get file screen nail", url: "/DCIM/$folderName/$fileName?act=scr", category: "storage", description: "" },
  { key: "get file create time", url: "/DCIM/$folderName/$fileName?act=ct", category: "storage", description: "" },
  { key: "get file info", url: "/DCIM/$folderName/$fileName?act=info", category: "storage", description: "" }
];

// 常用命令列表（用户可以根据需要修改）
const favorites = [
  "camera info",
  "start record", 
  "stop record",
  "stream0 settings",
  "stream1 settings",
  "get ip configuration",
  "clear setting",
  "reboot",
  "shutdown"
];

// 初始化命令描述- 批量设置所有命令的description字段
function initializeCommandDescriptions() {
  commands.forEach(cmd => {
    cmd.description = getCurrentCommandDescription(cmd.key);
  });
}

// 通过描述搜索命令 - 支持多语言搜索
function searchWithDescription(description) {
  const query = description.toLowerCase().trim();
  if (!query) return [];
  
  const matchedCommands = [];
  
  // 遍历所有命令
  commands.forEach(cmd => {
    // 检查所有语言的描述是否匹配
    for (const lang in commandDescriptions) {
      const langDescriptions = commandDescriptions[lang];
      if (langDescriptions && langDescriptions[cmd.key]) {
        const cmdDescription = langDescriptions[cmd.key].toLowerCase();
        if (cmdDescription.includes(query)) {
          // 找到匹配的命令，添加到结果中
          matchedCommands.push({
            ...cmd,
            matchedLanguage: lang,
            matchedDescription: langDescriptions[cmd.key]
          });
          break; // 找到一个匹配就跳出语言循环，避免重复
        }
      }
    }
  });
  
  return matchedCommands;
}

// 导出模块
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { commands, favorites, searchWithDescription };
}
  
